version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sphinx-bounties-postgres-dev
    environment:
      POSTGRES_DB: sphinx_bounties
      POSTGRES_USER: sphinx_bounties
      POSTGRES_PASSWORD: bounties_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sphinx_bounties -d sphinx_bounties"]
      interval: 10s
      timeout: 5s
      retries: 5

  sphinx-bounties-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sphinx-bounties-app-dev
    env_file:
      - .env.local
      - .env
    environment:
      - DATABASE_URL=postgresql://sphinx_bounties:bounties_password@postgres:5432/sphinx_bounties
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run dev

volumes:
  postgres_data_dev:
