export enum BountyStatus {
  DRAFT = "DRAFT",
  OPEN = "OPEN",
  ASSIGNED = "ASSIGNED",
  IN_REVIEW = "IN_REVIEW",
  PAID = "PAID",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum WorkspaceRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  CONTRIBUTOR = "CONTRIBUTOR",
  VIEWER = "VIEWER",
}

export enum ProgrammingLanguage {
  TYPESCRIPT = "TYPESCRIPT",
  JAVASCRIPT = "JAVASCRIPT",
  PYTHON = "PYTHON",
  RUST = "RUST",
  GO = "GO",
  JAVA = "JAVA",
  CSHARP = "CSHARP",
  CPP = "CPP",
  C = "C",
  RUBY = "RUBY",
  PHP = "PHP",
  SWIFT = "SWIFT",
  KOTLIN = "KOTLIN",
  DART = "DART",
  SOLIDITY = "SOLIDITY",
  OTHER = "OTHER",
}

export enum ProofStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
}

export enum BountyRequestStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum BountyActivityAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  ASSIGNED = "ASSIGNED",
  UNASSIGNED = "UNASSIGNED",
  PROOF_SUBMITTED = "PROOF_SUBMITTED",
  PROOF_REVIEWED = "PROOF_REVIEWED",
  COMPLETED = "COMPLETED",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  REQUESTED = "REQUESTED",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  REQUEST_REJECTED = "REQUEST_REJECTED",
}
